# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PhDownloader Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhDownloader Example
  pod 'PhDownloader', :path => '../'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end
