name: iOS Example Build CI

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:


jobs:
  build:
    name: Build "PhDownloader Example" scheme using any available iPhone simulator
    runs-on: macos-13
    defaults:
      run:
        working-directory: "PhDownloader Example"

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 'latest-stable'

      - name: Prepare and open Simulator
        run: |
          xcrun simctl create iphone-12-pro "iPhone 12 Pro"
          xcrun simctl boot iphone-12-pro
          open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app

      - uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod install
        run: pod install

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v3.0.0
        with:
          workspace: "PhDownloader Example/PhDownloader Example.xcworkspace"
          scheme: "PhDownloader Example"
          action: build
          sdk: iphonesimulator
          destination: platform=iOS Simulator,name=iphone-12-pro
          configuration: Debug
          build-settings: CODE_SIGNING_REQUIRED=NO
